### ISSUE TITLE
Add information to README

### ISSUE THREAD

**Issue by cbravo135** [mholtrop/EvioTool#1]
Please include instruction on dependencies and how to build this project in the README.
It would also be nice to have some instructions on how you run this.
Trying to build using a typical cmake workflow I get:
 
> In file included from /nfs/hps3/users/bravo/ana/svtHitFits/EvioTool/et-16.1/src/libsrc/et_jni.c:24:0:
> /nfs/hps3/users/bravo/ana/svtHitFits/EvioTool/et-16.1/src/libsrc/org_jlab_coda_et_EtJniAccess.h:2:17: > fatal error: jni.h: No such file or directory
> compilation terminated.
> et-16.1/CMakeFiles/et-jni-16.1.dir/build.make:62: recipe for target 'et-16.1/CMakeFiles/et-jni-16.1.dir/src/libsrc/et_jni.c.o' failed
> make[2]: *** [et-16.1/CMakeFiles/et-jni-16.1.dir/src/libsrc/et_jni.c.o] Error 1
> CMakeFiles/Makefile2:484: recipe for target 'et-16.1/CMakeFiles/et-jni-16.1.dir/all' failed
> make[1]: *** [et-16.1/CMakeFiles/et-jni-16.1.dir/all] Error 2
> Makefile:127: recipe for target 'all' failed
> make: *** [all] Error 2 

This makes me think that I am missing a dep or the cmake config files are wrong.

**Comment by mholtrop** [comment]
Go to https://github.com/JeffersonLab/EvioTool instead. Issues will be addressed there. :-)
